version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container_new
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: purchase project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
      
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container_new
    depends_on:
      - mysql
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
 
volumes:
  mysql_data:
